# Build stage
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -o main .

# Run stage
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]
